import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Simple translation function for now
const translations: Record<string, Record<string, string>> = {
  en: {
    'settings.title': 'Settings',
    'settings.description': 'Manage your app preferences and account settings',
    'settings.language': 'Language',
    'settings.language.description': 'Choose your preferred language',
    'language.english': 'English',
    'language.spanish': 'Spanish',
    'language.arabic': 'Arabic',
    'language.changed': 'Language changed to',
    'settings.notifications': 'Notifications',
    'settings.notifications.description': 'Get notified before scheduled workouts',
    'settings.notifications.progress': 'Progress Updates',
    'settings.notifications.progress.description': 'Weekly progress reports and achievements',
    'settings.notifications.meal': 'Meal Reminders',
    'settings.notifications.meal.description': 'Reminders for meals and hydration',
    'settings.notifications.social': 'Social Notifications',
    'settings.notifications.social.description': 'Messages from trainers and community',
    'settings.privacy': 'Privacy & Security',
    'settings.privacy.description': 'Control who can see your profile',
    'settings.privacy.data': 'Data Sharing',
    'settings.privacy.data.description': 'Control how your data is shared',
    'settings.privacy.2fa': 'Two-Factor Authentication',
    'settings.privacy.2fa.description': 'Add extra security to your account',
    'settings.privacy.password': 'Change Password',
    'settings.privacy.password.description': 'Update your account password',
    'settings.preferences': 'App Preferences',
    'settings.preferences.description': 'Switch to dark theme',
    'settings.preferences.units': 'Units',
    'settings.preferences.units.description': 'Weight and distance units',
    'workout.reminders': 'Workout Reminders',
    'progress.updates': 'Progress Updates',
    'meal.reminders': 'Meal Reminders',
    'social.notifications': 'Social Notifications',
    'profile.visibility': 'Profile Visibility',
    'data.sharing': 'Data Sharing',
    'two.factor.auth': 'Two-Factor Authentication',
    // 2FA specific status/messages (English)
    '2fa.enrollment.initiated': '2FA enrollment initiated. Please complete setup in your authenticator app.',
    '2fa.disabled': 'Two-factor authentication disabled.',
    '2fa.not.found': 'No TOTP factor found to disable.',
    '2fa.error': 'Failed to enable/disable 2FA.',
    'change.password': 'Change Password',
    'dark.mode': 'Dark Mode',
    'export.data': 'Export Data',
    'contact.support': 'Contact Support',
    'delete.account': 'Delete Account',
    'sign.out': 'Sign Out',
    'sign.out.description': 'Sign out of your account',
    'sign.out.success': 'Signed out successfully',
    'manage': 'Manage',
    'configure': 'Configure',
    'loading': 'Loading...',
    'enabled': 'enabled',
    'disabled': 'disabled',
    'disable': 'Disable',
    'enable': 'Enable',
    'update': 'Update',
    'export': 'Export',
    'contact': 'Contact',
    'delete': 'Delete',
    'units.changed': 'Units changed to',
    'data.export.requested': 'Data export requested',
    'data.export.description': 'Your data will be emailed to you shortly.',
    'data.export.error': 'Failed to export data',
    'settings.account': 'Account Management',
    'settings.account.description': 'Export your data or delete your account',
    'settings.account.support': 'Support',
    'settings.account.support.description': 'Get help from our support team',
    'settings.account.delete': 'Delete Account',
    // Profile visibility translations (cleaned up)
    'profile.visibility.title': 'Profile Visibility',
    'profile.visibility.description': 'Control who can see your profile information',
    'profile.visibility.level': 'Visibility Level',
    'profile.visibility.public': 'Public - Anyone can see your profile',
    'profile.visibility.connections': 'Connections Only - Only your connections can see your profile',
    'profile.visibility.private': 'Private - Only you can see your profile',
    // Adding password change / update translations
    'password.change.title': 'Change Password',
    'password.change.title': 'Cambiar Contraseña',
    'password.change.description': 'Actualiza la contraseña de tu cuenta',
    'password.change.current': 'Contraseña Actual',
    'password.change.new': 'Nueva Contraseña',
    'password.change.confirm': 'Confirmar Nueva Contraseña',
    'password.mismatch': 'Las contraseñas no coinciden',
    'password.updated': 'Contraseña actualizada exitosamente',
    'password.update.error': 'Error al actualizar la contraseña',
    // Newly added: message displayed when profile visibility is changed
    'profile.visibility.updated': 'Profile visibility updated',
    // Data sharing translations (cleaned up)
    'data.sharing.title': 'Data Sharing Preferences',
    'data.sharing.description': 'Control how your data is shared',
    'data.sharing.analytics': 'Analytics Data',
    'data.sharing.analytics.description': 'Share anonymous usage data to improve the app',
    'data.sharing.thirdparty': 'Third-Party Integration',
    'data.sharing.thirdparty.description': 'Comparte datos con servicios de terceros conectados',
    'data.sharing.marketing': 'Comunicaciones de Marketing',
    'data.sharing.marketing.description': 'Recibe ofertas y actualizaciones personalizadas',
    'data.sharing.updated': 'Preferencias de compartir datos actualizadas',
    // ... existing code ...
    'language.arabic': 'Arabic',
    'settings.notifications': 'Notifications',
    'settings.notifications.description': 'Receive notifications before scheduled workouts',
    'settings.notifications.progress': 'Progress Updates',
    'settings.notifications.progress.description': 'Weekly progress reports and achievements',
    'settings.notifications.meal': 'Meal Reminders',
    'settings.notifications.meal.description': 'Reminders for meals and hydration',
    'settings.notifications.social': 'Social Notifications',
    'settings.notifications.social.description': 'Messages from coaches and community',
    'settings.privacy': 'Privacy & Security',
    'settings.privacy.description': 'Control who can see your profile',
    'settings.privacy.data': 'Data Sharing',
    'delete': 'Eliminar',
    'units.changed': 'Unidades cambiadas a',
    'data.export.requested': 'Solicitud de exportación de datos',
    'data.export.description': 'Tus datos serán enviados a tu correo electrónico en breve.',
    'data.export.error': 'Error al exportar datos',
    'settings.privacy.data.description': 'Control how your data is shared',
    'settings.privacy.2fa': 'Two-Factor Authentication',
    'settings.privacy.2fa.description': 'Add extra security to your account',
    // Spanish translations for 2FA-related messages
    '2fa.enrollment.initiated': 'Registro de 2FA iniciado. Por favor, completa la configuración en tu aplicación de autenticación.',
    '2fa.disabled': 'Autenticación de dos factores desactivada.',
    '2fa.not.found': 'No se encontró factor TOTP para desactivar.',
    '2fa.error': 'Error al activar/desactivar 2FA.',
    'settings.privacy.password': 'Change Password',
    'settings.privacy.password.description': 'Update your account password',
    'settings.preferences': 'App Preferences',
    'settings.preferences.description': 'Customize your app experience',
    'settings.preferences.units': 'Units',
    'settings.preferences.units.description': 'Weight and distance units',
    'settings.account': 'Account Management',
    'settings.account.description': 'Export your data or delete your account',
    'settings.account.support': 'Support',
    'settings.account.support.description': 'Get help from our support team',
    'settings.account.delete': 'Delete Account',
    'settings.account.delete.description': 'Permanently delete your account and all data',
    'workout.reminders': 'Workout Reminders',
    'progress.updates': 'Progress Updates',
    'meal.reminders': 'Meal Reminders',
    'social.notifications': 'Social Notifications',
    'profile.visibility': 'Profile Visibility',
    // Spanish translations (added/missing)
    'profile.visibility.title': 'Visibilidad del Perfil',
    'profile.visibility.description': 'Controla quién puede ver la información de tu perfil',
    'profile.visibility.level': 'Nivel de Visibilidad',
    'profile.visibility.public': 'Público - Cualquiera puede ver tu perfil',
    'profile.visibility.connections': 'Solo Contactos - Solo tus contactos pueden ver tu perfil',
    'profile.visibility.private': 'Privado - Solo tú puedes ver tu perfil',
    'sign.out': 'تسجيل الخروج',
    'sign.out.description': 'تسجيل الخروج من حسابك',
    'sign.out.success': 'تم تسجيل الخروج بنجاح',
    'manage': 'إدارة',
    'profile.visibility.updated': 'Visibilidad del perfil actualizada',
    'data.sharing': 'Data Sharing',
    'data.sharing.title': 'Preferencias de Compartir Datos',
    'data.sharing.description': 'Controla cómo se comparten tus datos',
    'support.contact.placeholder': 'Describe your issue or question...',
    'support.message.required': 'Please enter a message',
    'support.request.sent': 'Support request sent',
    'support.request.description': 'We will respond to your inquiry within 24 hours.',
    'account.deletion.initiated': 'Account deletion initiated',
    'account.deletion.description': 'Your account will be deleted within 30 days.',
    'account.deletion.error': 'Failed to delete account',
    'two.factor.auth': 'المصادقة الثنائية',
    'change.password': 'تغيير كلمة المرور',
    'delete': 'حذف',
    'units.changed': 'تم تغيير الوحدات إلى',
    'data.export.requested': 'تم طلب تصدير البيانات',
    'data.export.description': 'سيتم إرسال بياناتك إلى بريدك الإلكتروني قريبًا.',
    'data.export.error': 'فشل في تصدير البيانات',
    'support.contact.placeholder': 'صف مشكلتك أو سؤالك...',
    'support.message.required': 'يرجى إدخال رسالة',
    'support.request.sent': 'تم إرسال طلب الدعم',
    'support.request.description': 'سنقوم بالرد على استفسارك خلال 24 ساعة.',
    'dark.mode': 'الوضع الداكن',
    'export.data': 'تصدير البيانات',
    'contact.support': 'الاتصال بالدعم',
    'delete.account': 'حذف الحساب',
    'sign.out': 'تسجيل الخروج',
    'sign.out.description': 'تسجيل الخروج من حسابك',
    'sign.out.success': 'تم تسجيل الخروج بنجاح',
    'manage': 'إدارة',
    'configure': 'تكوين',
    'loading': 'جار التحميل...',
    'enabled': 'مفعل',
    'disabled': 'معطل',
    'disable': 'تعطيل',
    'enable': 'تفعيل',
    'update': 'تحديث',
    'export': 'تصدير',
    'contact': 'اتصال',
    'delete': 'حذف',
    'units.changed': 'تم تغيير الوحدات إلى',
    // Arabic translations for password change messages
    'password.change.title': 'تغيير كلمة المرور',
    'password.change.description': 'حدث كلمة مرور حسابك',
    'password.change.current': 'كلمة المرور الحالية',
    'password.change.new': 'كلمة المرور الجديدة',
    'password.change.confirm': 'تأكيد كلمة المرور الجديدة',
    'password.mismatch': 'كلمات المرور غير متطابقة',
    'password.updated': 'تم تحديث كلمة المرور بنجاح',
    'password.update.error': 'فشل في تحديث كلمة المرور',
    '2fa.enrollment.initiated': 'تم بدء تسجيل المصادقة الثنائية. يرجى إكمال الإعداد في تطبيق المصادقة الخاص بك.',
    '2fa.disabled': 'تم تعطيل المصادقة الثنائية.',
    '2fa.not.found': 'لم يتم العثور على عامل TOTP لتعطيله.',
    '2fa.error': 'فشل في تفعيل/تعطيل المصادقة الثنائية.',
    'account.deletion.initiated': 'Eliminación de cuenta iniciada',
    'account.deletion.description': 'Tu cuenta será eliminada dentro de 30 días.',
    'account.deletion.error': 'Error al eliminar la cuenta',
    'profile.visibility.title': 'Profile Visibility',
    'profile.visibility.description': 'Control who can see your profile information',
    'support.contact.placeholder': 'Describe tu problema o pregunta...',
    'support.message.required': 'Por favor, introduce un mensaje',
    'support.request.sent': 'Solicitud de soporte enviada',
    'support.request.description': 'Responderemos a tu consulta dentro de 24 horas.',
    'profile.visibility.level': 'Visibility Level',
    'profile.visibility.public': 'Public - Anyone can see your profile',
    'profile.visibility.connections': 'Connections Only - Only your connections can see your profile',
    'profile.visibility.private': 'Private - Only you can see your profile',
    'profile.visibility.updated': 'تم تحديث رؤية الملف الشخصي',
    'data.sharing.title': 'Data Sharing Preferences',
    'data.sharing.description': 'Control how your data is shared',
    'data.sharing.analytics': 'Analytics Data',
    'data.sharing.analytics.description': 'Share anonymous usage data to improve the app',
    'data.sharing.thirdparty': 'Third-Party Integration',
    'data.sharing.thirdparty.description': 'Share data with connected third-party services',
    'data.sharing.marketing': 'Marketing Communications',
    'data.sharing.marketing.description': 'Receive personalized offers and updates',
    'data.sharing.updated': 'تم تحديث تفضيلات مشاركة البيانات',
    'password.change.title': 'Change Password',
    'password.change.description': 'Update your account password',
    'password.change.current': 'Current Password',
    'password.change.new': 'New Password',
    'password.change.confirm': 'Confirm New Password',
    'support.contact.title': 'Contact Support',
    'support.contact.description': 'Get help with your account or app issues',
    'support.contact.message': 'Message',
    'support.contact.placeholder': 'Describe your issue or question...',
    'account.delete.title': 'Delete Account',
    'account.delete.description': 'This action cannot be undone. Your account and all associated data will be permanently deleted.',
    'account.delete.confirm': 'Are you sure you want to delete your account?',
    'cancel': 'Cancel',
    'save.changes': 'Save Changes',
    'send.message': 'Send Message',
    'delete.account.confirm': 'Delete Account',
    'imperial': 'Imperial',
    'metric': 'Metric',
    // ... existing code ...
  },
  ar: {
    'settings.language': 'اللغة',
    'settings.language.description': 'اختر لغتك المفضلة',
    'language.english': 'الإنجليزية',
    'language.spanish': 'الإسبانية',
    'language.arabic': 'العربية',
    'settings.notifications': 'الإشعارات',
    'settings.notifications.description': 'احصل على إشعارات قبل جلسات التدريب المجدولة',
    'support.request.description': 'سنقوم بالرد على استفسارك خلال 24 ساعة.',
    'account.deletion.initiated': 'تم بدء حذف الحساب',
    'account.deletion.description': 'سيتم حذف حسابك خلال 30 يومًا.',
    'account.deletion.error': 'فشل في حذف الحساب',
    'settings.language.description': 'اختر لغتك المفضلة',
    'language.english': 'الإنجليزية',
    'language.spanish': 'الإسبانية',
    'language.arabic': 'العربية',
    'settings.notifications': 'الإشعارات',
    'settings.notifications.description': 'احصل على إشعارات قبل جلسات التدريب المجدولة',
    'settings.notifications.progress': 'تحديثات التقدم',
    'settings.notifications.progress.description': 'تقارير أسبوعية عن التقدم والإنجازات',
    'settings.notifications.meal': 'تذكيرات الوجبات',
    'settings.notifications.meal.description': 'تذكيرات للوجبات والترطيب',
    'settings.notifications.social': 'الإشعارات الاجتماعية',
    'settings.notifications.social.description': 'رسائل من المدربين والمجتمع',
    'settings.privacy': 'الخصوصية والأمان',
    'settings.privacy.description': 'تحكم في من يمكنه رؤية ملفك الشخصي',
    'settings.privacy.data': 'مشاركة البيانات',
    'settings.privacy.data.description': 'تحكم في كيفية مشاركة بياناتك',
    'settings.privacy.2fa': 'المصادقة الثنائية',
    'settings.privacy.2fa.description': 'أضف أمانًا إضافيًا إلى حسابك',
    'settings.privacy.password': 'تغيير كلمة المرور',
    'settings.privacy.password.description': 'حدث كلمة مرور حسابك',
    'settings.preferences': 'تفضيلات التطبيق',
    'settings.preferences.description': 'التبديل إلى السمة الداكنة',
    'settings.preferences.units': 'الوحدات',
    'settings.preferences.units.description': 'وحدات الوزن والمسافة',
    'settings.account': 'إدارة الحساب',
    'settings.account.description': 'قم بتصدير بياناتك أو حذف حسابك',
    'settings.account.support': 'الدعم',
    'settings.account.support.description': 'احصل على المساعدة من فريق الدعم لدينا',
    'settings.account.delete': 'حذف الحساب',
    'settings.account.delete.description': 'احذف حسابك وجميع البيانات بشكل دائم',
    'workout.reminders': 'تذكيرات التدريب',
    'progress.updates': 'تحديثات التقدم',
    'meal.reminders': 'تذكيرات الوجبات',
    'social.notifications': 'الإشعارات الاجتماعية',
    'profile.visibility': 'رؤية الملف الشخصي',
    'data.sharing': 'مشاركة البيانات',
    'two.factor.auth': 'المصادقة الثنائية',
    'change.password': 'تغيير كلمة المرور',
    'dark.mode': 'الوضع الداكن',
    'export.data': 'تصدير البيانات',
    'contact.support': 'الاتصال بالدعم',
    'delete.account': 'حذف الحساب',
    'sign.out': 'تسجيل الخروج',
    'sign.out.description': 'تسجيل الخروج من حسابك',
    'manage': 'إدارة',
    'configure': 'تكوين',
    'loading': 'جار التحميل...',
    'enabled': 'مفعل',
    'disabled': 'معطل',
    'disable': 'تعطيل',
    'enable': 'تفعيل',
    'update': 'تحديث',
    'export': 'تصدير',
    'contact': 'اتصال',
    'delete': 'حذف',
    'units.changed': 'تم تغيير الوحدات إلى',
    'profile.visibility.title': 'رؤية الملف الشخصي',
    'profile.visibility.description': 'تحكم في من يمكنه رؤية معلومات ملفك الشخصي',
    'profile.visibility.level': 'مستوى الرؤية',
    'profile.visibility.public': 'عام - يمكن لأي شخص رؤية ملفك الشخصي',
    'profile.visibility.connections': 'الاتصالات فقط - يمكن لاتصالاتك فقط رؤية ملفك الشخصي',
    'profile.visibility.private': 'خاص - يمكنك فقط رؤية ملفك الشخصي',
    'data.sharing.title': 'تفضيلات مشاركة البيانات',
    'data.sharing.description': 'تحكم في كيفية مشاركة بياناتك',
    'data.sharing.analytics': 'بيانات التحليلات',
    'data.sharing.analytics.description': 'شارك بيانات الاستخدام المجهولة لتحسين التطبيق',
    'data.sharing.thirdparty': 'التكامل مع طرف ثالث',
    'data.sharing.thirdparty.description': 'شارك البيانات مع خدمات الطرف الثالث المتصلة',
    'data.sharing.marketing': 'الاتصالات التسويقية',
    'data.sharing.marketing.description': 'تلقى عروضًا وتحديثات شخصية',
    'password.change.title': 'تغيير كلمة المرور',
    'password.change.description': 'حدث كلمة مرور حسابك',
    'password.change.current': 'كلمة المرور الحالية',
    'password.change.new': 'كلمة المرور الجديدة',
    'password.change.confirm': 'تأكيد كلمة المرور الجديدة',
    'support.contact.title': 'الاتصال بالدعم',
    'support.contact.description': 'احصل على المساعدة مع مشاكل حسابك أو التطبيق',
    'support.contact.message': 'الرسالة',
    'support.contact.placeholder': 'صف مشكلتك أو سؤالك...',
    'account.delete.title': 'حذف الحساب',
    'account.delete.description': 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف حسابك وجميع البيانات المرتبطة به بشكل دائم.',
    'account.delete.confirm': 'هل أنت متأكد أنك تريد حذف حسابك؟',
    'cancel': 'إلغاء',
    'save.changes': 'حفظ التغييرات',
    'send.message': 'إرسال الرسالة',
    'delete.account.confirm': 'حذف الحساب',
    'imperial': 'النظام الإمبراطوري',
    'metric': 'متري',
    // Add more translations here
  },
  es: {>>>>>>> REPLACE
    'settings.language': 'Idioma',
    'settings.language.description': 'Elige tu idioma preferido',
    'language.english': 'Inglés',
    'language.spanish': 'Español',
    'language.arabic': 'Árabe',
    'settings.notifications': 'Notificaciones',
    'settings.notifications.description': 'Recibe notificaciones antes de los entrenamientos programados',
    'settings.notifications.progress': 'Actualizaciones de Progreso',
    'settings.notifications.progress.description': 'Informes semanales de progreso y logros',
    'settings.notifications.meal': 'Recordatorios de Comida',
    'settings.notifications.meal.description': 'Recordatorios para comidas e hidratación',
    'settings.notifications.social': 'Notificaciones Sociales',
    'settings.notifications.social.description': 'Mensajes de entrenadores y comunidad',
    'settings.privacy': 'Privacidad y Seguridad',
    'settings.privacy.description': 'Controla quién puede ver tu perfil',
    'settings.privacy.data': 'Compartir Datos',
    'settings.privacy.data.description': 'Controla cómo se comparten tus datos',
    'settings.privacy.2fa': 'Autenticación de Dos Factores',
    'settings.privacy.2fa.description': 'Agrega seguridad adicional a tu cuenta',
    'settings.privacy.password': 'Cambiar Contraseña',
    'settings.privacy.password.description': 'Actualiza la contraseña de tu cuenta',
    'settings.preferences': 'Preferencias de la Aplicación',
    'settings.preferences.description': 'Cambiar al tema oscuro',
    'settings.preferences.units': 'Unidades',
    'settings.preferences.units.description': 'Unidades de peso y distancia',
    'settings.account': 'Gestión de Cuenta',
    'settings.account.description': 'Exporta tus datos o elimina tu cuenta',
    'settings.account.support': 'Soporte',
    'settings.account.support.description': 'Obtén ayuda de nuestro equipo de soporte',
    'settings.account.delete': 'Eliminar Cuenta',
    'settings.account.delete.description': 'Elimina permanentemente tu cuenta y todos los datos',
    'workout.reminders': 'Recordatorios de Entrenamiento',
    'progress.updates': 'Actualizaciones de Progreso',
    'meal.reminders': 'Recordatorios de Comida',
    'social.notifications': 'Notificaciones Sociales',
    'profile.visibility': 'Visibilidad del Perfil',
    'data.sharing': 'Compartir Datos',
    'two.factor.auth': 'Autenticación de Dos Factores',
    'change.password': 'Cambiar Contraseña',
    'dark.mode': 'Modo Oscuro',
    'export.data': 'Exportar Datos',
    'contact.support': 'Contactar Soporte',
    'delete.account': 'Eliminar Cuenta',
    'sign.out': 'Cerrar Sesión',
    // Add more translations here
  },
  ar: {
    'settings.language': 'اللغة',
    'settings.language.description': 'اختر لغتك المفضلة',
    'language.english': 'الإنجليزية',
    'language.spanish': 'الإسبانية',
    'language.arabic': 'العربية',
    'settings.notifications': 'الإشعارات',
    'settings.notifications.description': 'احصل على إشعارات قبل جلسات التدريب المجدولة',
    'settings.notifications.progress': 'تحديثات التقدم',
    'settings.notifications.progress.description': 'تقارير أسبوعية عن التقدم والإنجازات',
    'settings.notifications.meal': 'تذكيرات الوجبات',
    'settings.notifications.meal.description': 'تذكيرات للوجبات والترطيب',
    'settings.notifications.social': 'الإشعارات الاجتماعية',
    'settings.notifications.social.description': 'رسائل من المدربين والمجتمع',
    'settings.privacy': 'الخصوصية والأمان',
    'settings.privacy.description': 'تحكم في من يمكنه رؤية ملفك الشخصي',
    'settings.privacy.data': 'مشاركة البيانات',
    'settings.privacy.data.description': 'تحكم في كيفية مشاركة بياناتك',
    'settings.privacy.2fa': 'المصادقة الثنائية',
    'settings.privacy.2fa.description': 'أضف أمانًا إضافيًا إلى حسابك',
    'settings.privacy.password': 'تغيير كلمة المرور',
    'settings.privacy.password.description': 'حدث كلمة مرور حسابك',
    'settings.preferences': 'تفضيلات التطبيق',
    'settings.preferences.description': 'التبديل إلى السمة الداكنة',
    'settings.preferences.units': 'الوحدات',
    'settings.preferences.units.description': 'وحدات الوزن والمسافة',
    'settings.account': 'إدارة الحساب',
    'settings.account.description': 'قم بتصدير بياناتك أو حذف حسابك',
    'settings.account.support': 'الدعم',
    'settings.account.support.description': 'احصل على المساعدة من فريق الدعم لدينا',
    'settings.account.delete': 'حذف الحساب',
    'settings.account.delete.description': 'احذف حسابك وجميع البيانات بشكل دائم',
    'workout.reminders': 'تذكيرات التدريب',
    'progress.updates': 'تحديثات التقدم',
    'meal.reminders': 'تذكيرات الوجبات',
    'social.notifications': 'الإشعارات الاجتماعية',
    'profile.visibility': 'رؤية الملف الشخصي',
    'data.sharing': 'مشاركة البيانات',
    'two.factor.auth': 'المصادقة الثنائية',
    'change.password': 'تغيير كلمة المرور',
    'dark.mode': 'الوضع الداكن',
    'export.data': 'تصدير البيانات',
    'contact.support': 'الاتصال بالدعم',
    'delete.account': 'حذف الحساب',
    'sign.out': 'تسجيل الخروج',
    // Add more translations here
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>('en');

  // Load language from localStorage on initial render
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es' || savedLanguage === 'ar')) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('language', language);
    // Update document direction for RTL languages
    if (language === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl');
      document.documentElement.setAttribute('lang', 'ar');
    } else {
      document.documentElement.setAttribute('dir', 'ltr');
      document.documentElement.setAttribute('lang', language);
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const value = {
    language,
    setLanguage: (newLanguage: string) => {
      if (newLanguage === 'en' || newLanguage === 'es' || newLanguage === 'ar') {
        setLanguage(newLanguage);
      }
    },
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};