CREATE TABLE public.workouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.workouts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Trainers can manage their own workouts" ON public.workouts
  FOR ALL
  USING (auth.uid() = trainer_id);

CREATE TABLE public.workout_exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workout_id BIGINT NOT NULL REFERENCES public.workouts(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  sets INTEGER NOT NULL,
  reps TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.workout_exercises ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Trainers can manage exercises for their workouts" ON public.workout_exercises
  FOR ALL
  USING (EXISTS (SELECT 1 FROM public.workouts WHERE id = workout_id AND trainer_id = auth.uid()));

CREATE POLICY "Athletes can view exercises for their assigned workouts" ON public.workout_exercises
  FOR SELECT
  USING (EXISTS (SELECT 1 FROM public.workout_assignments WHERE workout_id = workout_exercises.workout_id AND athlete_id = auth.uid()));
