CREATE TABLE public.workout_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workout_id BIGINT NOT NULL REFERENCES public.workouts(id) ON DELETE CASCADE,
  athlete_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  trainer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  assigned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  due_date DATE,
  status TEXT NOT NULL DEFAULT 'pending'
);

ALTER TABLE public.workout_assignments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Trainers can manage their own workout assignments" ON public.workout_assignments
  FOR ALL
  USING (auth.uid() = trainer_id);

CREATE POLICY "Athletes can view their own workout assignments" ON public.workout_assignments
  FOR SELECT
  USING (auth.uid() = athlete_id);
