// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfgenblmkkxisidvdbkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmZ2VuYmxta2t4aXNpZHZkYmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjMzNzMsImV4cCI6MjA2NTU5OTM3M30.re4Phxrp7RRcvvCVFYgGuc0Kk1PUmDiv9THWUqAbtmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);