// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://yfgenblmkkxisidvdbkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmZ2VuYmxta2t4aXNpZHZkYmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjMzNzMsImV4cCI6MjA2NTU5OTM3M30.re4Phxrp7RRcvvCVFYgGuc0Kk1PUmDiv9THWUqAbtmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom fetch with longer timeout for Edge Functions
const customFetch = (url: RequestInfo | URL, options?: RequestInit) => {
  const timeout = 30000; // 30 seconds timeout
  return Promise.race([
    fetch(url, options),
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error("Request timed out")), timeout),
    ),
  ]) as Promise<Response>;
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: customFetch,
      headers: {
        "X-Client-Info": "fit-pathway-organizer",
      },
    },
  },
);
